# Assignment Day 15

# 1. Create a 3x3x3 array with random values 

In [13]:
import numpy as np
arr = np.empty((3,3,3))
arr

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
        [1.37962117e-306, 1.24608550e-306, 7.56587585e-307],
        [1.37961302e-306, 1.05699242e-307, 8.01097889e-307]],

       [[1.78020169e-306, 7.56601165e-307, 1.02359984e-306],
        [1.15710088e-306, 6.23056330e-307, 1.60219578e-306],
        [7.56601165e-307, 6.23061763e-307, 9.34607074e-307]],

       [[8.90098127e-307, 8.90108313e-307, 6.23053954e-307],
        [8.90104239e-307, 1.86919513e-306, 1.11261570e-306],
        [1.42410974e-306, 1.42404727e-306, 5.97819431e-322]]])

In [14]:
arr.shape

(3, 3, 3)

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [8]:
arr1 = np.diag(1+np.arange(4), k = -1)
print (arr1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [9]:
arr1.shape

(5, 5)

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [22]:
import numpy as np
print("Checkerboard pattern:\n")
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

Checkerboard pattern:

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
a.shape

(8, 8)

# 4. Normalize a 5x5 random matrix

In [31]:
x= np.random.random((3,3))
print("Original Array:\n")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("\nAfter normalization:\n")
print(x)

Original Array:

[[0.21978548 0.17111949 0.14358208]
 [0.29082151 0.00587146 0.50139239]
 [0.14152946 0.58055059 0.31393837]]

After normalization:

[[0.37223211 0.28754834 0.23963045]
 [0.49584201 0.         0.8622567 ]
 [0.23605868 1.         0.53606769]]


In [32]:
x.shape

(3, 3)

# 5.  How to find common values between two arrays?

In [34]:
arr01 = np.array([0, 1, 2, 3, 4])
print("Array1 : ",arr01)
arr02 = [1, 3, 5]
print("Array2 : ",arr02)
print("\nCommon values between two arrays:")
print(np.intersect1d(arr01, arr02))

Array1 :  [0 1 2 3 4]
Array2 :  [1, 3, 5]

Common values between two arrays:
[1 3]


# 6.How to get the dates of yesterday, today and tomorrow?

In [39]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("\nToday: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("\nTomorrow: ",tomorrow)

Yestraday:  2020-07-24

Today:  2020-07-25

Tomorrow:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [54]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("\nSecond array:")
print(y)
print("\nAbove two arrays are equal")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 0 0 0 0 1]

Second array:
[0 0 1 1 1 0]

Above two arrays are equal
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [94]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("\nMaximum value replaced by 0:")
print(x)

Original array:
[0.53955069 0.36487066 0.75508091 0.09333462 0.11181616 0.56927512
 0.23537351 0.19293912 0.27403437 0.89953759]

Maximum value replaced by 0:
[0.53955069 0.36487066 0.75508091 0.09333462 0.11181616 0.56927512
 0.23537351 0.19293912 0.27403437 0.        ]


# 9. How to print all the values of an array?

In [62]:
import numpy as np
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [64]:
print("Original matrix:\n")
X = np.random.rand(4, 4)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.34542579 0.95834801 0.09517052 0.98153097]
 [0.3201273  0.25370064 0.33009881 0.77447531]
 [0.90583364 0.5984356  0.67159254 0.07607209]
 [0.39870689 0.85849688 0.14517214 0.09401484]]

Subtract the mean of each row of the said matrix:

[[-0.24969304  0.36322919 -0.4999483   0.38641215]
 [-0.09947321 -0.16589988 -0.0895017   0.35487479]
 [ 0.34285017  0.03545213  0.10860907 -0.48691138]
 [ 0.0246092   0.48439919 -0.22892554 -0.28008285]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [87]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

np.add.at(Z, I, 1)
print(Z)

[2. 2. 3. 2. 2. 2. 3. 4. 5. 5.]
[3. 3. 5. 3. 3. 3. 5. 7. 9. 9.]


# 12.How to get the diagonal of a dot product?

In [71]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Array 1 :')
print(X)
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('\nArray 2 :')
print(Y)
Z = np.diag(X.dot(Y))
print('\nDiagonal of a dot product')
print(Z)

Array 1 :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2 :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal of a dot product
[ 30  81 150]


# 13.How to find the most frequent value in an array?

In [80]:
x = np.random.randint(0, 10, 30)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[9 2 2 6 3 4 4 2 1 2 0 5 0 2 5 3 5 9 7 1 7 3 5 7 4 5 1 1 7 7]
Most frequent value in the above array:
2


# 14.How to get the n largest values of an array

In [82]:
x = np.arange(20)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19]


# 15.How to create a record array from a regular array?

In [84]:
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                  ("Ayaana Mcnamara", 87, 99),
                  ("Jody Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,names='col1, col2, col3',formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Yasemin Rayner', 88.5, 90) (b'Ayaana Mcnamara', 87. , 99)
 (b'Jody Preece', 85.5, 91)]
